---
docker_enabled: true

docker_users: []

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_remove_conflicting_packages:
  - docker.io
  - docker-compose
  - docker-compose-v2
  - docker-doc
  - podman-docker
  - containerd
  - runc

# Astra Docker repository settings
docker_astra_use_official_repo: true
docker_astra_debian_codename: "stretch"
docker_astra_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_astra_optional_packages:
  - docker-buildx-plugin
  - docker-compose-plugin

docker_min_supported_version: "24.0.0"
docker_allow_unsupported_astra_version: false