# Base system packages for all workstations
base_packages:
  - curl
  - wget
  - git
  - vim
  - ca-certificates
  - unzip

# System timezone
base_timezone: "Europe/Moscow"

# System locale
base_locale: "en_US.UTF-8"

base_hostname: ~
base_manage_hosts_file: true
