---
users:
  - name: ansible
    state: present
    shell: /bin/bash
    groups:
      - sudo
    ssh_keys:
      - "~/.ssh/diplom.pub"
    sudo: true
    sudo_nopasswd: true

  - name: devuser
    state: present
    shell: /bin/bash
    groups: []
    ssh_keys:
      - "~/.ssh/diplom.pub"
    sudo: false
    sudo_nopasswd: false


security_ssh_allow_users:
  - ansible
  - devuser
  
docker_users:
  - devuser
  
dev_users:
  - devuser

dev_git_config_enabled: true
dev_git_user_name: "Dev User"
dev_git_user_email: "devuser@example.com"