# SSH configuration

security_ssh_port: 22

security_ssh_permit_root_login: "no"
security_ssh_password_authentication: "no"
security_ssh_pubkey_authentication: "yes"

# Ограничения пользователей
security_ssh_allow_users:
  - devuser

# Restart ssh after config change
security_ssh_restart: true

#SSH hardening v2
security_ssh_max_auth_tries: 3
security_ssh_login_grace_time: 30
security_ssh_client_alive_interval: 300
security_ssh_client_alive_count_max: 2

# Fail2ban

security_fail2ban_enabled: true
security_fail2ban_maxretry: 5
security_fail2ban_bantime: 600

# Firewall 

security_firewall_enabled: true
security_firewall_allowed_ports:
  - 22
