---
- name: Update apt cache on Ubuntu
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base packages on Ubuntu
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present

- name: Set timezone on Ubuntu
  community.general.timezone:
    name: "{{ base_timezone }}"

- name: Ensure locale package is installed on Ubuntu
  ansible.builtin.apt:
    name: locales
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Generate locale on Ubuntu
  ansible.builtin.locale_gen:
    name: "{{ base_locale }}"
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Set system locale on Ubuntu
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: 'LANG={{ base_locale }}'
    create: true
